"""TIER LIVE client plumbing — the browser-side mirror stub (P6a step 4).

The JS below is what the P6b ticker pages embed for on-demand symbols. Its
contract, in order:
1. read ``data/verdicts/contract.json`` — the SAME scoring contract the Python
   engine exports; the mirror never re-hardcodes a number;
2. if a worker URL is configured, fetch ``/bars/<SYMBOL>`` and compute the few
   components price history allows (trend, drawdown) — the missing dials stay
   dark and INSUFFICIENT EVIDENCE gates exactly as in Python;
3. if no worker is configured (the default), render the DEGRADATION message —
   stated, never silent.
"""

from __future__ import annotations

import json
from pathlib import Path

DEGRADATION_MESSAGE = (
    "add to watchlist — full verdict on tomorrow's build "
    "(no live worker configured; nothing is computed on the spot)"
)

CONTRACT_PATH = "data/verdicts/contract.json"


def tier_live_js(worker_url: str = "") -> str:
    """The embeddable client stub. ``worker_url`` empty = degradation mode."""
    return f"""
// TIER LIVE mirror — reads the engine's contract; never re-hardcodes numbers
var TIER_LIVE = {{
  workerUrl: {worker_url!r},
  contractUrl: {CONTRACT_PATH!r},
  degradation: {DEGRADATION_MESSAGE!r},
  verdict: async function(symbol) {{
    if (!this.workerUrl) return {{ label: null, note: this.degradation }};
    var contract = await (await fetch(this.contractUrl)).json();
    var res = await fetch(this.workerUrl + '/bars/' + encodeURIComponent(symbol));
    if (!res.ok) return {{ label: contract.insufficient_label,
                           note: 'live bars unavailable (' + res.status + ')' }};
    var chart = await res.json();
    var closes = (((chart.chart || {{}}).result || [])[0] || {{}}).indicators;
    closes = closes && closes.quote && closes.quote[0] ? closes.quote[0].close : null;
    // filter nulls BEFORE the length gate — sparse data must gate, not NaN
    closes = (closes || []).filter(function(c) {{ return c != null; }});
    if (closes.length < 40) return {{ label: contract.insufficient_label,
                                      note: 'not enough price history' }};
    var n = closes.length, last = closes[n-1];
    var trend = Math.max(-1, Math.min(1, (last / closes[Math.max(0, n-64)] - 1) * 4));
    var peak = -Infinity, dd = 0;
    for (var i = 0; i < n; i++) {{ peak = Math.max(peak, closes[i]);
      dd = Math.max(dd, 1 - closes[i] / peak); }}
    // one lit component ("trend") -> coverage below the contract floor by
    // design: the honest on-demand answer is INSUFFICIENT EVIDENCE with the
    // dials that ARE known shown. Watchlisting unlocks the full engine.
    return {{ label: contract.insufficient_label,
              dials: {{ expected_return: Math.round(trend * 1e4) / 1e4,
                        drawdown_risk: Math.round(dd * 1e4) / 1e4 }},
              note: 'live price-only preview — ' +
                    'coverage below the ' + Math.round(contract.min_weight_coverage * 100) +
                    '% evidence floor; add to watchlist for the full verdict' }};
  }}
}};
"""


def write_universe_json(out_dir: Path | str) -> Path:
    """site/universe.json — the full listed-symbol set the home search lazy-fetches
    (same-origin) to tell 'listed but unbuilt' from 'not a listed symbol'."""
    from ..sources.instruments import InstrumentRegistry

    out = Path(out_dir) / "universe.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    # mutual funds are searchable too (P6e) — their pages score via ETF twins
    out.write_text(json.dumps(InstrumentRegistry().symbols(
        kinds=("stock", "etf", "mutual_fund"))), encoding="utf-8")
    return out


def emit_worker_allowlist(path: Path | str | None = None) -> Path:
    """Generate the worker's allowlist module from the registry — the registry
    IS the allowlist (Codex review: shape validation alone leaves a general
    quote proxy). Regenerated by ``flab-verdicts`` so it tracks listings."""
    from ..config import PATHS
    from ..sources.instruments import InstrumentRegistry

    if path is None:
        path = PATHS.root / "workers" / "quote-proxy" / "allowlist.js"
    path = Path(path)
    symbols = InstrumentRegistry().symbols()
    js = ("// GENERATED by flab-verdicts from the instrument registry — do not hand-edit\n"
          f"export const ALLOWED_SYMBOLS = new Set({json.dumps(symbols)});\n")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(js, encoding="utf-8")
    return path
